# Generated by Django 2.2.5 on 2020-03-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('about_description', models.TextField(default='')),
                ('company_name', models.TextField(default='')),
                ('professional_description', models.TextField(default='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
