# Generated by Django 3.0.4 on 2020-03-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_simple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='about_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='company_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='location',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='professional_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
